chassis_driver:
  ros__parameters:
    port: /dev/ttyUSB_chassis
    baudrate: 19200
    serial_timeout: 0.5
    send_interval: 0.1
    gear_ratio: 50.0
    wheel_radius: 0.2032
    wheel_separation: 0.6221
    cmd_left_direction: 1
    cmd_right_direction: 1
    fb_left_direction: 1
    fb_right_direction: 1
    publish_tf: true
    cmd_vel_timeout: 0.5